"""First migration

Revision ID: 054c8d61bd34
Revises: 
Create Date: 2021-05-11 09:39:53.429728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054c8d61bd34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('water_temp', sa.Float(), nullable=False),
    sa.Column('uv_level', sa.String(length=5), nullable=False),
    sa.Column('uv_time', sa.Integer(), nullable=False),
    sa.Column('weather_conditions', sa.String(length=255), nullable=False),
    sa.Column('outside_temp', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('pool')
    # ### end Alembic commands ###
